library(dplyr)
data("MechaCar_mpg")
install.packages("tidyverse")
install.packages("jsonlite")
library(dplyr)
MechaCar_mpg <- read.csv("MechaCar_mpg.csv")
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, MechaCar_mpg))
Suspension_Coil <- read.csv("Suspension_Coil.csv")
total_summary <- Suspension_Coil %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary <- Suspension_Coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
sample_table <- Suspension_Coil %>% sample_n(50)
t.test(sample_table$PSI,mu=mean(Suspension_Coil$PSI))
t.test(sample_table$PSI, mu=1500)
t.test(subset(Suspension_Coil$PSI, Suspension_Coil$Manufacturing_Lot == "Lot1"), mu=total_summary$Mean) 
t.test(subset(Suspension_Coil$PSI, Suspension_Coil$Manufacturing_Lot == "Lot2"), mu=total_summary$Mean) 
t.test(subset(Suspension_Coil$PSI, Suspension_Coil$Manufacturing_Lot == "Lot3"), mu=total_summary$Mean)
